name: Deploy to Vercel

on:
  push:
    branches:
      - rest_app  # メインブランチへのプッシュ時に実行
  pull_request:
    branches:
      - rest_app  # プルリクエスト時にもプレビューデプロイを実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Deploy to Vercel
        if: github.event_name == 'push'
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        
      - name: Preview Deploy to Vercel
        if: github.event_name == 'pull_request'
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --yes
